# Generated by Django 4.2.6 on 2023-10-10 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
        ('converted_songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertedsong',
            name='song',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='converted_songs', to='songs.song'),
        ),
    ]
