# Generated by Django 4.2.6 on 2023-12-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_alter_song_options'),
        ('converted_songs', '0002_convertedsong_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convertedsong',
            name='song',
        ),
        migrations.AddField(
            model_name='convertedsong',
            name='song',
            field=models.ManyToManyField(blank=True, related_name='converted_songs', to='songs.song'),
        ),
    ]
