# Generated by Django 4.2.6 on 2023-10-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(default=0, upload_to='downloads/'),
            preserve_default=False,
        ),
    ]
