# Generated by Django 4.2.6 on 2023-10-21 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_alter_song_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['id']},
        ),
    ]
